name: CMake

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: apt install -y gcc g++ gdb make cmake libwxgtk3.0-gtk3-dev && mkdir build

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: make all

      - name: Execute
        working-directory: ${{github.workspace}}/build
        run: ./audio
