name: CMake

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: sudo apt install -y gcc g++ gdb make cmake libwxgtk3.0-gtk3-dev libcurl4-openssl-dev && mkdir build
        run: wget -P ${{github.workspace}}/thirdparty/ http://uk.un4seen.com/files/bass24-linux.zip && cd ${{github.workspace}}/thirdparty && unzip bass24-linux.zip bass.h x64/libbass.so && rm bass24-linux.zip

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: make all
