name: CMake

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: make all

      - name: Execute
        working-directory: ${{github.workspace}}/build
        run: ./audio
